"""The migration must actually run -- models alone don't prove that."""

from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

BACKEND_ROOT = Path(__file__).resolve().parents[1]


def _alembic_config(db_url: str) -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.set_main_option("sqlalchemy.url", db_url)
    return config


def test_upgrade_head_creates_the_change_log(tmp_path, monkeypatch):
    db_path = tmp_path / "migration_check.db"
    db_url = f"sqlite:///{db_path}"
    # env.py reads settings.database_url, which is resolved at import time.
    monkeypatch.setattr("app.config.settings.database_url", db_url)

    command.upgrade(_alembic_config(db_url), "head")

    inspector = inspect(create_engine(db_url))
    assert "change_log" in inspector.get_table_names()
    assert "applied_result" in {c["name"] for c in inspector.get_columns("agent_actions")}

    indexes = {ix["name"] for ix in inspector.get_indexes("change_log")}
    assert "ix_change_log_entity" in indexes


def test_downgrade_unwinds_the_whole_schema(tmp_path, monkeypatch):
    """Revision-agnostic: going to base must leave nothing behind.

    Asserting on one migration's table broke the moment a later one
    became head.
    """
    db_path = tmp_path / "downgrade_check.db"
    db_url = f"sqlite:///{db_path}"
    monkeypatch.setattr("app.config.settings.database_url", db_url)
    config = _alembic_config(db_url)

    command.upgrade(config, "head")
    inspector = inspect(create_engine(db_url))
    assert {"change_log", "recipe_items", "agent_runs"} <= set(inspector.get_table_names())

    command.downgrade(config, "base")

    remaining = set(inspect(create_engine(db_url)).get_table_names()) - {"alembic_version"}
    assert remaining == set()


def test_head_migration_round_trips(tmp_path, monkeypatch):
    """Down one step and back up must reproduce the head schema exactly.

    Checks whichever migration is newest, instead of naming its table --
    the version that did broke each time a migration was added.
    """
    db_path = tmp_path / "round_trip.db"
    db_url = f"sqlite:///{db_path}"
    monkeypatch.setattr("app.config.settings.database_url", db_url)
    config = _alembic_config(db_url)

    def schema():
        inspector = inspect(create_engine(db_url))
        return {
            table: sorted(column["name"] for column in inspector.get_columns(table))
            for table in inspector.get_table_names()
        }

    command.upgrade(config, "head")
    at_head = schema()

    command.downgrade(config, "-1")
    assert schema() != at_head  # the step actually removed something

    command.upgrade(config, "head")
    assert schema() == at_head


# --- Postgres -------------------------------------------------------------
# The migrations were autogenerated against SQLite, so they are only known to
# work on Postgres if they are run there. Skipped unless TEST_DATABASE_URL
# points at a Postgres server (CI provides one).

import os  # noqa: E402

import pytest  # noqa: E402

POSTGRES_URL = os.environ.get("TEST_DATABASE_URL", "")
requires_postgres = pytest.mark.skipif(
    not POSTGRES_URL.startswith("postgres"), reason="needs TEST_DATABASE_URL for Postgres"
)


def _reset_postgres_schema():
    from sqlalchemy import text

    from app.db.session import engine

    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))


@requires_postgres
def test_postgres_upgrade_and_full_downgrade(monkeypatch):
    from app.db.session import Base, engine, normalize_database_url

    url = normalize_database_url(POSTGRES_URL)
    monkeypatch.setattr("app.config.settings.database_url", url)
    config = _alembic_config(url)

    _reset_postgres_schema()
    try:
        command.upgrade(config, "head")
        tables = set(inspect(engine).get_table_names())
        assert {"change_log", "recipe_items", "agent_runs", "orders"} <= tables

        command.downgrade(config, "base")
        assert set(inspect(engine).get_table_names()) - {"alembic_version"} == set()
    finally:
        # Leave the schema as the other tests expect it.
        _reset_postgres_schema()
        Base.metadata.create_all(engine)
