"""add promotion expiry to menu_items

Revision ID: 8454fa470db9
Revises: 95b108f65b06
Create Date: 2026-09-12 23:39:49.335758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8454fa470db9'
down_revision: Union[str, Sequence[str], None] = '95b108f65b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('regular_price', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('promo_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'promo_ends_at')
    op.drop_column('menu_items', 'regular_price')
    # ### end Alembic commands ###
