"""add change_log and agent_action applied_result

Revision ID: a649971e1021
Revises: efd4e0aab222
Create Date: 2026-09-11 19:16:12.899200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a649971e1021'
down_revision: Union[str, Sequence[str], None] = 'efd4e0aab222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('agent_run_id', sa.String(length=32), nullable=True),
    sa.Column('agent_action_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_log_agent_run_id', 'change_log', ['agent_run_id'], unique=False)
    op.create_index('ix_change_log_entity', 'change_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_change_log_ts', 'change_log', ['ts'], unique=False)
    op.add_column('agent_actions', sa.Column('applied_result', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_actions', 'applied_result')
    op.drop_index('ix_change_log_ts', table_name='change_log')
    op.drop_index('ix_change_log_entity', table_name='change_log')
    op.drop_index('ix_change_log_agent_run_id', table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
